### ISSUE TITLE
capacity of logstash container

### ISSUE THREAD

**Issue by amulyas** [cloudfoundry-community/logstash-docker-boshrelease#6]
I noticed a problem where logstash container stop working and kibana throwing 
ERR Syslog Sink syslog://1.2.3.4:12345: Error when dialing out. Backing off for 1.016ms. Err: dial tcp 1.2.3.4:12345: connection refused
restarting container just that container only fixed the problem .. the service instance bind with mutiple application like 15 at same time, do you see any issues in capacity like how many apps can push data at same time or CPU or memory assigned to container ...

**Comment by drnic** [comment]
@amulyas did you ever solve this?

**Comment by amulyas** [comment]
Yes its not the case anymore this should be closed
